spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
#    username: root
#    password: root1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.spring.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
  

        