spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/parkingapi?useSSL=false
    username: rootparking
    password: rootparking
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.spring.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect